pruebaEjemplo: pruebaEjemplo.c arbolBB.o
	gcc -g -DEJERCICIO_ENTREGA pruebaEjemplo.c arbolBB.o -o pruebaEjemplo
arbolBB.o: arbolBB.h arbolBB.c
	gcc -c -g -DEJERCICIO_ENTREGA arbolBB.c -o arbolBB.o
clean:
	rm *.o
